services:
  - type: web
    name: task-manager-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_JWT_EXPIRATION_MS
        value: 86400000

  - type: static_site
    name: task-manager-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://task-manager-backend.onrender.com
